simplified spawn function name

diff --git a/bash/_bash_aliases b/bash/_bash_aliases
--- a/bash/_bash_aliases
+++ b/bash/_bash_aliases
@@ -43,12 +43,13 @@ alias mnt=mount
 }
 
 # start program
-spawn() {
+# spawn() {
+s() {
     if [ "$1" ]; then
 	"$@" &>/dev/null &
 	disown $!
     else
-	echo "Error: No command given" >&2
+	echo "Error [spawn]: No command given" >&2
 	return 1
     fi
 }
